### ISSUE TITLE
Wywołanie metody niezgodne z definicją

### ISSUE THREAD

**Issue by snacaman** [tpay-com/tpay-php#12]
Wywołanie metody [src](https://github.com/tpay-com/tpay-php/blob/71405e2ba4d081973d5b66e4ddb099d3a9603f77/tpayLibs/src/_class_tpay/PaymentForms/PaymentCardForms.php#L112):

`$resp = $this->presale($cliAuth, $desc);`

jest niezgodne z definicją [src](https://github.com/tpay-com/tpay-php/blob/71405e2ba4d081973d5b66e4ddb099d3a9603f77/tpayLibs/src/_class_tpay/PaymentCard.php#L76):

`public function presale($description, $cliAuth)`

**Comment by piotrjozwiak** [comment]
Ta metoda jest już nieobsługiwana i została usunięta przez commit c835b07d788dbef13aaa7eb96a8983e3eb3deafe
Do obciążenie zapamiętanej karty należy skorzystać z metod presale i sale podobnie jak w example tpay-https://github.com/tpay-com/tpay-php/blob/master/tpayLibs/examples/RecurrentPayment.php
