### ISSUE TITLE
bank selection

### ISSUE THREAD

**Issue by piotrm73** [tpay-com/tpay-php#14]
![image](https://user-images.githubusercontent.com/23495580/56419749-af2e2280-629b-11e9-82fb-6ade7f34fb5f.png)

hi
there is something wrong with bank selection display

**Comment by piotrjozwiak** [comment]
@piotrm73 please take a look at console if there are some JS errors.

**Comment by piotrm73** [comment]
yep there was a problem with the path to styles http://localhost:8000/src/View/Styles/style.css, I copied it to another location and form looks ok. 

one more question, how to change language? I was trying (new Lang())->setLang('pl') but there is no effect

thanks

**Comment by piotrjozwiak** [comment]
@piotrm73 you can change any frontend form language by adding
`(new Util())->setLanguage('pl');`
before method getting the form body.
Also if there are some problems with static files like style.css or JS, you can set any custom path to those files by running
`$Util->setPath('path/to/static/files');`
where $Util is the instance of Util class.

**Comment by piotrm73** [comment]
now it's working... I had to create directories View/Styles under path_to_static, now it's looks like this: path_to_static/View/Styles/style.css

thanks for your help
