### ISSUE TITLE
Dodanie Util::$templateDirectory na wzór  Util::$libraryPath

### ISSUE THREAD

**Issue by hoRacy** [tpay-com/tpay-php#15]
Bardzo przydałaby się możliwość nadpisywania folderu z templatkami w configu $templateDirectory, tak jak przy $libraryPath, gdzie nadpisanie np. Util::$libraryPath = '/vendor/tpay/'; załatwia temat.
Dlaczego? W domyślnej templatce CardGate ładowane jest jquery i zachowania tego NIE MOŻNA nadpisać w chwili obecnej.

https://github.com/tpay-com/tpay-php/blob/master/tpayLibs/src/_class_tpay/Utilities/Util.php#L41

**Comment by piotrjozwiak** [comment]
Dziękujemy za zgłoszenie. Dodaliśmy opisaną funkcjonalność w commit 46afbde5f6e713bcced68e34b9bf9ac785ccf603

**Comment by hoRacy** [comment]
Bardzo dziękuję, ale...
tak średnio bym powiedział, tak średnio.

Jest błąd w is_null() - Powinno być: 
`  if (is_null(static::$customTemplateDirectory)) {
            $templateDirectory = dirname(__FILE__) . '/../../View/Templates/';
        } else {
            $templateDirectory =  static::$customTemplateDirectory;
        }`

**Comment by piotrjozwiak** [comment]
@hoRacy przepraszamy za niedopatrzenie. Poprawka została wypchnięta. 3d8cf241e1743784f20025df1e1431dd28d1a71e
