### ISSUE TITLE
PaymentSMS and enableJSONResponse

### ISSUE THREAD

**Issue by Digital87** [tpay-com/tpay-php#18]
Hey, 

Are you 100% sure that the PaymentSMS works? 
_doSmsRequest_ sends a request by CURL to http://sms.tpay.com/widget/verifyCode.php and then a response in given (two numbers separent with a new line \n) the isValidCode method is ready for it, but the requests method sets  _->enableJSONResponse()_  and that throws "Error decoding response to JSON". 

Second thing is that PaymentSMS::secureURL should be **https** not http. I checked it works!
Third thing http://sms.tpay.com/widget/verifyCode.php works for POST and GET is this ok? 

I can make a PR to fix this Like make Json response an option in requests method but still are yousure  http://sms.tpay.com/widget/verifyCode.php should not return json?

**Comment by piotrjozwiak** [comment]
Hi @Digital87 
This payment was not updated for a few years, so we have just tested and updated the library to work as expected by this commit e90fbc23c151728941820309544da3d3c8e3922b
Please take a look at the SmsNotification example and check if that works for you.

**Comment by Digital87** [comment]
The functionality works and the link is on https. Thanks! :)

By the way I got just a small observation. I noticed that there are handy control attributes like "loggingEnabled" and "customLogPatch". Shouldn't it be "customLogPath" instad of "customLogPatch" ?

**Comment by Digital87** [comment]
Case closed ;)
