### ISSUE TITLE
Płatność blik - testowy kod

### ISSUE THREAD

**Issue by elenril2** [tpay-com/tpay-php#19]
Chciałbym się dowiedzieć jaki testowy kod Blik można wykorzystać w przykładzie BlikPayment. Dane (123456) wskazane w dokumentacji https://support.tpay.com/en/case-study/wdrozenie-metody-blik wydają się nie działać dla tej klasy, przy standardowych poświadczeniach z ExamplesConfig.

**Comment by piotrjozwiak** [comment]
Dzień dobry
"123456" jest poprawnym kodem BLIK dla kont działających w trybie testowym. W takim trybie działa również biblioteka z domyślnym config'iem. Jaki błąd jest zwracany?

**Comment by elenril2** [comment]
Dziękuję za błyskawiczną odpowiedź. Funkcja processPayment wchodzi w stan, wskazujący, że został przesłany nieprawidłowy kod - The BLIK code was incorrect, redirect to transaction panel to try again.
W zmiennej $_POST['blik_code'] jest wartość 123456.

**Comment by piotrjozwiak** [comment]
Prosimy sprawdzić logi z komunikacji API, które powinny automatycznie utworzyć się w https://github.com/tpay-com/tpay-php/tree/master/tpayLibs/src/Logs

**Comment by elenril2** [comment]
===========================
Outgoing request
===========================
2020-09-04 10:54:34
ip: 192.168.2.109
URL: https://api.tpay.com/transactions/ta_jrkNGjRd3WaGbqwe/pay 
 Method: POST 
 Fields: {"groupId":150,"method":"transfer","blikPaymentData":{"blikToken":"123456","type":0}} 
 Headers: ["Authorization: Bearer b9f93f4ceed71816186b26501ac538ca16becc34","Content-Type: application\/json"]

===========================
Request response
===========================
2020-09-04 10:54:35
ip: 192.168.2.109
Fields: {"result":"failed","requestId":"NvWrKmD5ga4B6LbdyzgNrw3Xpok2YxP1RMzJOj0w","errors":[{"errorCode":"blik_error","errorMessage":"Podany kod jest nieprawid\u0142owy, b\u0105d\u017a utraci\u0142 wa\u017cno\u015b\u0107.","fieldName":"blikPaymentData","devMessage":"Blik transaction processing error","docUrl":"https:\/\/openapi.tpay.com\/#\/transactions\/post_transactions"},{"errorCode":"payment_failed","errorMessage":"Payment failed","fieldName":"","devMessage":"Please try again later","docUrl":"https:\/\/openapi.tpay.com\/#\/transactions\/post_transactions"}]} 
 HTTP code: 400

**Comment by piotrjozwiak** [comment]
The issue is open in the wrong repository. You are using the https://github.com/tpay-com/tpay-openapi-php repository, which relates to different API version, which has not the sandbox mode yet.
So to make the payment, you need the production BLIK code.
