### ISSUE TITLE
Lack of pack ID in mass payment creation response 

### ISSUE THREAD

**Issue by lamberski** [tpay-com/tpay-php#2]
There's a a bug in `tpay\TransactionApi` class that prevents from reading ID of the pack created in `masspaymentCreate()`. According to documentation (api-mass-payment_1.1.pdf, page 3), ID of the created package is located under element called `pack_id`, but in SDK (https://github.com/tpay-com/tpay-php/blob/master/src/_class_tpay/transactionApi.php#L372) `<packId>` is used instead.

Changing line 374 to below, fixes this problem.

```php
// Before
static::PACK_ID => Util::findSubstring('/<packId>(.*)<\/packId>/', $res),

// After
static::PACK_ID => Util::findSubstring('/<pack_id>(.*)<\/pack_id>/', $res),
```

**Comment by piotrjozwiak** [comment]
That was refactoring mistake.
Changes have been [merged](https://github.com/tpay-com/tpay-php/commit/3f1dfc6f8fb6242b102106192a2880f939ef4c68).
