### ISSUE TITLE
parametr onetimer i sign

### ISSUE THREAD

**Issue by simplo-marcind** [tpay-com/tpay-php#22]
Witam,
Podczas implementacji nowego sposobu podpisu żądań API do kart płatniczych, wykryłęm błąd w bibliotece.

https://github.com/tpay-com/tpay-php/blob/d2ac79460a1e30d3113b3d5288e2f66a25816e3e/tpayLibs/src/_class_tpay/CardApi.php#L45

Nie działa przykład przy zaznaczeniu "Save my card"
https://github.com/tpay-com/tpay-php/blob/d2ac79460a1e30d3113b3d5288e2f66a25816e3e/tpayLibs/examples/CardGate.php

**Comment by piotrjozwiak** [comment]
Poprawka jest już w drodze, prosimy o cierpliwość.

**Comment by piotrjozwiak** [comment]
4baa585ff1db8dd70cd777201f403561b7e46dd4 rozwiązuje wspomniany problem.
