### ISSUE TITLE
Aktualizacja biblioteki pod nowy sposób liczenia md5

### ISSUE THREAD

**Issue by hoRacy** [tpay-com/tpay-php#24]
Witam.
W kilku miejscach biblioteka nie nadąża za zmianą sposobu liczenia md5:
https://support.tpay.com/pl/aktualizacja-sposobu-liczenia-sumy-kontrolnej

Komentarze:
https://github.com/tpay-com/tpay-php/blob/c52f979cc928e84269096284feaf5aab98577505/tpayLibs/src/Dictionaries/Payments/BasicFieldsDictionary.php#L398

Wyliczenie:
https://github.com/tpay-com/tpay-php/blob/c52f979cc928e84269096284feaf5aab98577505/tpayLibs/src/_class_tpay/Notifications/BasicNotificationHandler.php#L68

Pozdrawiam.

**Comment by piotrjozwiak** [comment]
Witaj @hoRacy 
Zmiana nie dotyczy asynchronicznych powiadomień o transakcjach.
