### ISSUE TITLE
Aktualizacja isMd5Valid w BasicNotificationHandler

### ISSUE THREAD

**Issue by kkraszy** [tpay-com/tpay-php#25]
Witam, 
Prawdopodobnie należy zaktualizować funkcję isMd5Valid w klasie BasicNotificationHandler ze względu na zmianę w obliczaniu sumy kontrolnej. Według nowych wytycznych funkcja powinna wyglądać następująco:  

`    private function isMd5Valid($md5sum, $transactionAmount, $crc)
    {
        if (!is_string($md5sum) || strlen($md5sum) !== 32) {
            return false;
        }
        return ($md5sum === md5($this->merchantId .'&'. $this->transactionID .'&'. 
                $transactionAmount .'&'. $crc .'&'. $this->merchantSecret));
    }  `

**Comment by piotrjozwiak** [comment]
Witaj @kkraszy 
Aktualizacja tego miejsca nie jest wymagana, gdyż zmiana sposobu liczenia nie dotyczy powiadomień o wpłatach. Analogiczny issue został ostatnio zamknięty z tego samego powodu https://github.com/tpay-com/tpay-php/issues/24

**Comment by bielas** [comment]
@piotrjozwiak jak w takim razie powinno to wygladac? mam trzy rozne sposoby:
md5("1010." + command.getTransactionId().getValue() + "." + command.getTransactionAmount() + "." + command.getTransactionCrc() + "." + merchantSecurityCode);

md5("1010.&." + command.getTransactionId().getValue() + ".&." + command.getTransactionAmount() + ".&." + command.getTransactionCrc() + ".&." + merchantSecurityCode);

md5("1010&" + command.getTransactionId().getValue() + "&" + command.getTransactionAmount() + "&" + command.getTransactionCrc() + "&" + merchantSecurityCode);

zadne przyklad nie jest w stanie wygenerowac md5sum takiej jak do mnie wyslaliscie?
