### ISSUE TITLE
Demo credentials

### ISSUE THREAD

**Issue by zachu90** [tpay-com/tpay-php#26]
I am trying to use Card API, with the credentials provided in this [demo](https://github.com/tpay-com/tpay-php/blob/master/tpayLibs/examples/CardPaymentLinkBuilder.php)

The demo credentials I am using:

```
        $this->cardApiKey = 'bda5eda723bf1ae71a82e90a249803d3f852248d';
        $this->cardApiPass = 'IhZVgraNcZoWPLgA';
        $this->cardKeyRSA = 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdRQ2NLRTVZNU1Wemd5a1Z5ODNMS1NTTFlEMEVrU2xadTRVZm1STS8NCmM5L0NtMENuVDM2ekU0L2dMRzBSYzQwODRHNmIzU3l5NVpvZ1kwQXFOVU5vUEptUUZGVyswdXJacU8yNFRCQkxCcU10TTVYSllDaVQNCmVpNkx3RUIyNnpPOFZocW9SK0tiRS92K1l1YlFhNGQ0cWtHU0IzeHBhSUJncllrT2o0aFJDOXk0WXdJREFRQUINCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ';
        $this->cardVerificationCode = '6680181602d396e640cb091ea5418171';
        $this->cardHashAlg = 'sha1';

```
Every time I am getting response with code 10, which I believe is auth error.

```
array (size=2)
  'result' => int 0
  'err_code' => int 10
```

Have the demo credentials changed, or am I doing something wrong ?

**Comment by piotrjozwiak** [comment]
Hi @zachu90 we have reseted the demo credentials. Please use the
IhZVgraNcZoWPLgA1yQcGMIzquVWWrWtJ
as cardApiPass and let me know if it is working now.

**Comment by zachu90** [comment]
@piotrjozwiak thanks, it's working now
