### ISSUE TITLE
Error code 5

### ISSUE THREAD

**Issue by lSanik** [tpay-com/tpay-php#27]
https://github.com/tpay-com/tpay-php/blob/c52f979cc928e84269096284feaf5aab98577505/tpayLibs/src/_class_tpay/Refunds/CardRefunds.php#L49

Hello! I'm update library for tpay payments (card api).
After update Payments work well, but refunds is error  have ["err_code"]=> int(5) after update library. 
If i change line to old 
- $params[CardDictionary::SIGN] = hash($this->cardHashAlg, implode('', $params) . $this->cardVerificationCode)  
Working great. 

Can you help me plz?) 
Library standart. No custom difference betwen versions. 
Thx!

**Comment by piotrjozwiak** [comment]
Hi @lSanik 
The issue is resolved now by commit 161e2cdecb497ab0e54a0eaa7c3962b7d5563abd
