### ISSUE TITLE
Cards API metoda `securesale` zwraca nieprawidłowy kod HTTP 602

### ISSUE THREAD

**Issue by pszalko** [tpay-com/tpay-php#29]
Serwer TPay zwraca nieprawidłowy kod odpowiedzi HTTP 602 w przypadku udanej transakcji `securesale`.

**Comment by piotrjozwiak** [comment]
Witaj @pszalko 
Kod zwracany przez serwer Tpay jest niepoprawny i rozwiązanie problemu leży raczej po stronie aplikacji Tpay, a nie biblioteki.
Kod 602 jest w zasadzie nieprawidłowym kodem HTTP, więc dostosowanie biblioteki do takiego kodu mija się z celem.
Niebawem błąd zostanie usunięty po stronie aplikacji.
Dziękujemy za zgłoszenie.
