### ISSUE TITLE
Ability to install via composer

### ISSUE THREAD

**Issue by lamberski** [tpay-com/tpay-php#3]
Right now there's no way to install SDK by using composer, which is basically a norm right now in PHP world. I have to use _hack_ which is to manually define package in my composer file. See this for reference: https://getcomposer.org/doc/05-repositories.md#package-2.

It would be much better to be able to just run:

```
composer require tpay-com/tpay-php
```

And have the package installed automatically. See how your competition does it: [composer.json](https://github.com/PayU/openpayu_php/blob/master/composer.json). 😜

**Comment by Anatejms** [comment]
there's a way but if admins will be changing whole lib without notice this is pointless. Now I have to refactor bunch of code -.-

to use composer simply do:
`"autoload": {
		"psr-4": {
			"": "src/"
		},
		"files": [
			"vendor/tpay-com/tpay-php/src/_class_tpay/paymentBasic.php",
			"vendor/tpay-com/tpay-php/src/_class_tpay/lang.php"
		]
	},
	"repositories": {
		"tpay-com/tpay-php": {
			"type": "package",
			"package": {
				"name": "tpay-com/tpay-php",
				"version": "1",
				"source": {
					"url": "https://github.com/tpay-com/tpay-php",
					"type": "git",
					"reference": "master"
				}
			}
		}
	},`

and then in require section:
`"tpay-com/tpay-php": "*",`

**Comment by lamberski** [comment]
Thanks for the reply! Yes, that's exactly what I'm doing right now — defining local package in my _composer.json_. I just thought that it would be good idea to add it to this repository, so other developers don't need to spent time and do it manually like I had to.

> Now I have to refactor bunch of code -.-

I don't understand what's the problem here. The point of creating public repository with library to integrate your payment system with your client's application is to ease this process, right? Thanks to such library clients don't need to go through the docs and manually write code to handle each request & response to the payment system. It saves time and maybe even is increasing number of your clients thanks to easy process of integrating your service with their app.

If you're providing the library like this — do it right. Otherwise, you're just testing patience of the developers by serving half-baked & not-so-tested-it-seems library.

**Comment by lamberski** [comment]
Thanks for the reply! Yes, that's exactly what I'm doing right now — defining local package in my composer.json. I just thought that it would be good idea to add it to this repository, so other developers don't need to spent time and do it manually like I had to.

> Now I have to refactor bunch of code -.-

~~I don't understand what's the problem here. The point of creating public repository with library to integrate your payment system with your client's application is to ease this process, right? Thanks to such library clients don't need to go through the docs and manually write code to handle each request & response to the payment system. It saves time and maybe even is increasing number of your clients thanks to easy process of integrating your service with their app.~~

~~If you're providing the library like this — do it right. Otherwise, you're just testing patience of the developers by serving half-baked & not-so-tested-it-seems library.~~

> there's a way but if admins will be changing whole lib without notice this is pointless.

~~Why would anyone want to modify code of library if it's well designed and easily configurable through its API?~~

---

@Anatejms Sorry for this first comment! I have misunderstood it and took you as one of the maintainers of this library. 🙃

Yes, and that's exactly the problem with lack of versioning and composer support. You cannot just lock version of the library at some specific one and be safe. With manually created approach you're always at risk that maintainers will make some breaking changes and break your application.

**Comment by piotrjozwiak** [comment]
Your issue has been resolved.
Please type the following commands:
composer update
composer require tpay-com/tpay-php
