### ISSUE TITLE
Problems with parseTemplate. 

### ISSUE THREAD

**Issue by zimdin12** [tpay-com/tpay-php#31]
In parseTemplate @L64(`$parsedHTML = ob_get_contents();`) & L65(`ob_clean();`) are cousing my page to break. Header of my page is misplaced inside of the rendered tpay html. I am using blade templating engine. If I replace L64 with `$parsedHTML = ob_get_clean();` and remove L65 then everything is working well and other parts of the site are fine. Does somebody have good solution so i would not have to fork this repo ?

**Comment by mzawodzinski** [comment]
This template system is completely no sense and stupid.
Templates and logs system makes this lib almost useless.
Please remove this, lib should return raw data not templates.

**Comment by gstarczyk** [comment]
Hi @zimdin12 
Can you provide some exemplary "blade" template where this issue occurs?

I cannot reproduce such behaviour.

**Comment by zimdin12** [comment]
I just updated deps and I can confirm that this has been fixed on 2.4.7. 
Now i have cleaner code without weird temp overrides :D
