### ISSUE TITLE
How to disable curl verbose mode?

### ISSUE THREAD

**Issue by luigifab** [tpay-com/tpay-php#32]
Is there a simple way to disable curl verbose mode?

Like: `\tpayLibs\src\_class_tpay\Utilities\Util::$loggingEnabled = false;`
For example: `\tpayLibs\src\_class_tpay\Curl\CurlOptions::$verbose = false;`

**Comment by luigifab** [comment]
If I can update the curl timeout in the same way for `BasicReports`... because it is slow when with many transactions, even for 1 day.

**Comment by piotrjozwiak** [comment]
The verbose can be edited the same way like described in https://github.com/tpay-com/tpay-php/issues/33#issuecomment-1004824265

Just use additionally `$this->curl->disableVerbose();`

The timeout is the same `$this->curl->setTimeout(60);`
