### ISSUE TITLE
Broken notification when used with multiple reverse proxy

### ISSUE THREAD

**Issue by AdamWyzgol** [tpay-com/tpay-php#34]
In case when site is located behind more then one reverse proxy validation of X-Forwarded-For for exact match of one of ip is not sufficiant, there should be ability to use more then one ip in X-Forwarded-For or just validate x-real-ip

**Comment by piotrjozwiak** [comment]
All the extra attributes like x-real-id, x-forwarded-for can be tricked easily.

The option to validate x-forwarder-for should be used only for testing purposes. On production, you should configure your proxy to pass the original visitor address like described here https://support.cloudflare.com/hc/en-us/articles/200170786 and disable forwarded ip validation in this library.
