### ISSUE TITLE
Sprawdzanie md5sum z danymi z notification url 

### ISSUE THREAD

**Issue by bielas** [tpay-com/tpay-php#36]
Chce sprawdzic czy md5sum ktora przyszla do mnie wraz z notification url jest zgodna z moimi danymi. Do tego celu probuje w jakis sposob zaszyfrowac dane aby potem moc porownac z tym co mi przyszlo. Niestety dokumentacja zawiera braki/rozne rozwiazania. Pondato ponizej przesylam trzy rozne sposoby jak aktualnie generuje md5sum do sprawdzenia jednak zaden wynik nie jest taki sam jak ten ktory przyszedl do mnie wraz z notification url. Czy moge uzyskac informacje w jakis spsob po swojej stronie mam wygenerowac md5sume?

md5("1010." + command.getTransactionId().getValue() + "." + command.getTransactionAmount() + "." + command.getTransactionCrc() + "." + merchantSecurityCode);

md5("1010.&." + command.getTransactionId().getValue() + ".&." + command.getTransactionAmount() + ".&." + command.getTransactionCrc() + ".&." + merchantSecurityCode);

md5("1010&" + command.getTransactionId().getValue() + "&" + command.getTransactionAmount() + "&" + command.getTransactionCrc() + "&" + merchantSecurityCode);

**Comment by BanczerowskiM** [comment]
Witaj @bielas, 

Suma kontrolna dla notyfikacji ma wzór md5(IDMerchnata + IDTransakcji + KwotaTranskcji + KodCRC + KodBezpieczeństwa);
gdzie znak plusa jest znakiem konkatenacji. 

Jedynie dla sumy kontrolnej, która generuje transakcje umieszczany znak & pomiędzy jej wartościami.
