### ISSUE TITLE
Test masspayments api credentials

### ISSUE THREAD

**Issue by JeRabix** [tpay-com/tpay-php#41]
I use test credentials for masspayments API

```
# TPAY
TPAY_SECRET="demo"
TPAY_MERCHANT_ID="1010"
TPAY_API_KEY="75f86137a6635df826e3efe2e66f7c9a946fdde1"
TPAY_API_PASS="p@$$w0rd#@!"
```

but for api method create massPayments i have error - "0 : Access denied (via Merchant Panel settings) in file /var/www/html/vendor/tpay-com/tpay-php/tpayLibs/src/_class_tpay/TransactionApi.php line: 121"

**Comment by BanczerowskiM** [comment]
Function masspayment is disabled on demo account. If you want to use this function, you have to turn on your production account. 
Please contact merchant service to get it started on your account: https://tpay.com/en#contact
