### ISSUE TITLE
Fatal error: Arrays are not allowed in class constants & Case sensitive file class

### ISSUE THREAD

**Issue by Tomirad** [tpay-com/tpay-php#6]
This mistake I have inline 50, validate.php for PHP version 5.5:
`50:  const REG = array(...);`

Second problem as Case sensitive file patch.
File have first letter lowercase and class name have first letter uppercase. PSR specification recommend MUST for case sensitive namespace for file patch & class name.

**Comment by piotrjozwiak** [comment]
Ok, we have made it combined as strings instead of array.
The sonarcube tells us to rename this files if we make them like TestClass. It should be testClass and class declared in code as TestClass. In fact you always use /tpay/TestClass as reference in tpay namespace so file name is not important.

**Comment by Tomirad** [comment]
Not important for you.  But important for framework PHP with autoloader.
Please read: http://www.php-fig.org/psr/psr-4/

**Comment by piotrjozwiak** [comment]
Currently the code is being adjusted to be valid PSR2. We will make it PSR4 in future.
