### ISSUE TITLE
Validate param 'opis' - limited signs

### ISSUE THREAD

**Issue by Tomirad** [tpay-com/tpay-php#8]
Documentation allowed in param `opis` all type of sign with limited lenght 128. Class tpay-php return me error with sentence: "Zamówienie 999/2017". 

In PHP is such thing as [filter_var](http://php.net/manual/en/function.filter-var.php). It is much better than regular expression with mistakes.

**Comment by piotrjozwiak** [comment]
Slashes has been allowed [adf7347](https://github.com/tpay-com/tpay-php/commit/2f2a5d63c71a543cfcba34bf6149c67a05eeae4b)
