### ISSUE TITLE
Undefined $_POST variable type

### ISSUE THREAD

**Issue by vuer** [tpay-com/tpay-php#9]
Create new PR, because current version always returns error:
"Undefined $_POST variable type in file /Users/wuer/Projects/rentumi-api/vendor/tpay-com/tpay-php/tpayLibs/src/_class_tpay/Utilities/Util.php line: 120"

\tpayLibs\src\_class_tpay\Notifications\BasicNotificationHandler

dev-master version with fixed validation works fine.

**Comment by piotrjozwiak** [comment]
The new version (2.0.2) has been released.
Thank you.
